# @package backbone
_target_: models.PointceptBackbone
name: sonata # name can be rewritten to a local checkpoint path 
repo_id: facebook/sonata
model_lib: sonata
custom_config:
  enc_mode: False
decoder_serializations:
  - "standard"


